# Linear Algebra

### Arithmetic Operation of Vectors


In [23]:
import numpy as np

A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [-3, 4]])

print(f"A + B= \n{A+B}")

print(f"\nAB = \n{A*B}")

print(f"\n3A - 2B =\n{3*A-2*B}")


A + B= 
[[ 3  1]
 [-3  7]]

AB = 
[[ 2 -2]
 [ 0 12]]

3A - 2B =
[[ 4 -7]
 [ 6  1]]


### Inverse and determinant of matrix

In [24]:
A = np.array([[2, -1], [0, 3]])
A_det= np.linalg.det(A)
print(f"The determinant of the given matrix \n{A_det}")

if A_det == 0:
    print(" = 0")
    print("\nInverse of the matrix isn't possible")

else:
    print(f"The inverse of the matrix:\n {np.linalg.inv(A)}")

The determinant of the given matrix 
6.0
The inverse of the matrix:
 [[0.5        0.16666667]
 [0.         0.33333333]]


### Eigenvalues and Eigenvectors  

In [25]:
C = np.array([[4, 1], [-2, 1]])

print(f"Say the given vector is \n C = \n{C}")
E_value , E_vector = np.linalg.eig(C)
print(f"\n The eigen value for C is \n{E_value}")
print(f"\n The Eigen vector is \n{E_vector}")

Say the given vector is 
 C = 
[[ 4  1]
 [-2  1]]

 The eigen value for C is 
[3. 2.]

 The Eigen vector is 
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


### Price prediction