# Linear Algebra

### Arithmetic Operation of Vectors


Q.1) Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]
a. A+B
b. AB
c. 3A−2B

In [23]:
import numpy as np

A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [-3, 4]])

print(f"A + B= \n{A+B}")

print(f"\nAB = \n{A*B}")

print(f"\n3A - 2B =\n{3*A-2*B}")


A + B= 
[[ 3  1]
 [-3  7]]

AB = 
[[ 2 -2]
 [ 0 12]]

3A - 2B =
[[ 4 -7]
 [ 6  1]]


---


### Inverse and determinant of matrix

Q.2) Find the determinant of A.
Determine whether A is invertible. If yes, calculate A−1.

In [24]:
A = np.array([[2, -1], [0, 3]])
A_det= np.linalg.det(A)
print(f"The determinant of the given matrix \n{A_det}")

if A_det == 0:
    print(" = 0")
    print("\nInverse of the matrix isn't possible")

else:
    print(f"The inverse of the matrix:\n {np.linalg.inv(A)}")

The determinant of the given matrix 
6.0
The inverse of the matrix:
 [[0.5        0.16666667]
 [0.         0.33333333]]


---


### Eigenvalues and Eigenvectors  

Q.2) Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]

In [25]:
C = np.array([[4, 1], [-2, 1]])

print(f"Say the given vector is \n C = \n{C}")
E_value , E_vector = np.linalg.eig(C)
print(f"\n The eigen value for C is \n{E_value}")
print(f"\n The Eigen vector is \n{E_vector}")

Say the given vector is 
 C = 
[[ 4  1]
 [-2  1]]

 The eigen value for C is 
[3. 2.]

 The Eigen vector is 
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


---

### Price prediction

Q.3) You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1:
x1: 4
x2:  1.5
x3: 100
and price: 20

car 2:
x1: 6
x2:  2.0
x3: 150
and price: 30

Then, find the price of a car 3 with features
x1: 8
x2:  3.0
x3: 200
price:?

In [28]:
import numpy

X = np.array([[4,6],
              [1.5,2], 
              [100,150]])
Y= np.array([20,30])
B = X.T@X
Be = np.linalg.inv(B)
Bet = Be@X.T
Beta = Bet.T@Y
print(Beta)
m = np.array([8,
             3.0,
             200])
print("The pridicted value of the car is:")
print(Beta@m)


[7.98722045e-03 1.42108547e-13 1.99680511e-01]
The pridicted value of the car is:
39.99999999927965


---
